### ISSUE TITLE
Bug report: ia client introduced breaking change with regards to credential storage location

### ISSUE THREAD

**Issue by Moocow93** [bibanon/tubeup#172] opened 2021-09-02 00:17 UTC
**Checklist**

- [x] I have fully updated tubeup, youtube-dl and internetarchive along with their associated dependencies.
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the issues (closed or open) for similar bug reports including closed ones
- [x] I am not submitting a bug report about S3 timeouts (we have no control over Internet Archive outages or per-user throttling)
- [x] I've checked the Twitter account of Internet Archive (@internetarchive) for any announced outages or planned infrastructure maintenance that would affect performance of uploads.
- [x] I have properly indented [with triple backticks before and after the console output](https://guides.github.com/pdfs/markdown-cheatsheet-online.pdf) full terminal terminal output from the line where the command was run to where I was returned to command prompt, and am not trying to obscure item identifiers or URLs used in the creation of the bug (we need this to recreate the bug or investigate what happened).

**Dependency versions**

Please provide version information from core dependencies:

`ia --version`
2.1.0
**Expected behavior**
The video should download and then upload the files to archive.org
**Additional context**
This happens with any other video I try to archive. Going back to internetarchive 2.0.3 fixes this problem.

```
$ tubeup https://www.youtube.com/watch?v=kJQP7kiw5Fk
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.7.3 (CPython) - Linux-5.4.120+-x86_64-with-debian-10.10
[debug] exe versions: ffmpeg 4.1.6-1, ffprobe 4.1.6-1
[debug] Proxy map: {}
[debug] Default format spec: bestvideo+bestaudio/best
There are no annotations to write.
Requested formats are incompatible for merge and will be merged into mkv.
[download] 100.0% of 120.22MiB at 179.35MiB/s ETA 00:00
{'downloaded_bytes': 126059374, 'total_bytes': 126059374, 'filename': '/home/drjeffsmith15432/.tubeup/downloads/kJQP7kiw5Fk.f137.mp4', 'status': 'finished', 'elapsed': 0.8422536849975586, '_total_bytes_str': '120.22MiB', '_elapsed_str': '00:00'}
Downloaded /home/drjeffsmith15432/.tubeup/downloads/kJQP7kiw5Fk.f137.mp4
[download] 100.0% of 4.39MiB at 172.31MiB/s ETA 00:00
{'downloaded_bytes': 4605080, 'total_bytes': 4605080, 'filename': '/home/drjeffsmith15432/.tubeup/downloads/kJQP7kiw5Fk.f251.webm', 'status': 'finished', 'elapsed': 0.03972268104553223, '_total_bytes_str': '4.39MiB', '_elapsed_str': '00:00'}
Downloaded /home/drjeffsmith15432/.tubeup/downloads/kJQP7kiw5Fk.f251.webm

An exception just occured, if you found this exception isn't related with any of your connection problem, please report this issue to https://github.com/bibanon/tubeup/issues
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tubeup/__main__.py", line 99, in main
    use_download_archive):
  File "/usr/local/lib/python3.7/dist-packages/tubeup/TubeUp.py", line 381, in archive_urls
    identifier, meta = self.upload_ia(basename, custom_meta)
  File "/usr/local/lib/python3.7/dist-packages/tubeup/TubeUp.py", line 332, in upload_ia
    parsed_ia_s3_config = parse_config_file(self.ia_config_path)[1]['s3']
TypeError: 'bool' object is not subscriptable
```

**Comment by brandongalbraith** [comment] 2021-09-02 00:28
I am aware of this issue and looking into the regression.

**Comment by vxbinaca** [comment] 2021-09-02 00:40
My guess is one of the commits between 2.0.3 and 2.1.0 of `internetarchive`. Speaking of regressions I appear to have messed up the issue template somehow. Will investigate later.

Thanks for fixing the issue by the way @Moocow93

**Comment by vxbinaca** [comment] 2021-09-28 02:42
I want to close this but shouldn't because it's not resolved technically yet, I just did the FlexSeal coding thing where I lock the dep for `internetarchive` to a working version while slaying another dragon. 

So to-be-continued.

**Comment by brandongalbraith** [comment] 2021-10-03 16:35
For detecting ia.ini, [tubeup should attempt the following paths in this order, using the first existing file](https://github.com/jjjake/internetarchive/pull/405#issue-875978495):

* `${XDG_CONFIG_HOME}/internetarchive/ia.ini` (with `XDG_CONFIG_HOME` defaulting to `${HOME}/.config` if not set or invalid)
* `~/.config/ia.ini`
* `~/.ia`

**Comment by vxbinaca** [comment] 2021-10-03 16:41
Unfortunately this won't work I tried to reconfigure 2.1.0 and that still wasn't taking.

**Comment by brandongalbraith** [comment] 2021-10-03 19:45
Note to self to notify https://github.com/etnguyen03/docker-tubeup/pull/88 when this is fixed.

**Comment by soredake** [comment] 2021-12-24 08:33
Any progress on this?

**Comment by vxbinaca** [comment] 2021-12-25 04:23
Upgrade Tubeup, I locked `internetarchive` to the last non-broken version as a Flex Seal fix.

**Comment by soredake** [comment] 2022-01-01 08:25
`pipx install tubeup` temporary solution for me

**Comment by vxbinaca** [comment] 2022-04-16 00:25
This is the last major dragon in the code. Everything else is minor (output verbosity) or a feature request. and thanks everyone for their participation so far.

**Closed** 2022-06-10 21:31 UTC
Labels: bug
