### ISSUE TITLE
Make Filenames Deterministic

### ISSUE THREAD

**Issue by brandongalbraith** [bibanon/tubeup#73] opened 2018-10-16 16:53 UTC
Confirmed tubeup is where the fix needs to be. youtube-dl downloads successfully to my local workstation. Looking for suggestions on what would be considered "safe" for sanitizing the tweet body to support a "safe" filename; we maintain the tweet identifier after the `-` deliminator.

```
tubeup https://twitter.com/StevieBuckley/status/1051762443851112448
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.10.05
[debug] Python version 3.7.0 (CPython) - Darwin-18.0.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.0.1, ffprobe 4.0.1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
There are no annotations to write.
[download] 100.0% of ~2.61MiB at 746.84KiB/s ETA 00:00
{'downloaded_bytes': 2739348, 'total_bytes': 2739348, 'filename': '/Users/brandon/.tubeup/downloads/Stevie_Buckley_-_Managed_to_get_myself_blocked_on_LinkedIn_for_saying_that_this_is_the_best_parody_of_the_recruitment_industry_I_ve_ever_seen._Turns_out_Haigh_Associates_were_actually_being_sincer...-1051762443851112448.mp4', 'status': 'finished', 'elapsed': 5.218930959701538, '_total_bytes_str': '2.61MiB', '_elapsed_str': '00:05'}
Downloaded /Users/brandon/.tubeup/downloads/Stevie_Buckley_-_Managed_to_get_myself_blocked_on_LinkedIn_for_saying_that_this_is_the_best_parody_of_the_recruitment_industry_I_ve_ever_seen._Turns_out_Haigh_Associates_were_actually_being_sincer...-1051762443851112448.mp4
1051762443851112448: malformed AAC bitstream detected.

An exception just occured, if you found this exception isn't related with any of your connection problem, please report this issue to https://github.com/bibanon/tubeup/issues
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/tubeup/__main__.py", line 91, in main
    use_download_archive):
  File "/usr/local/lib/python3.7/site-packages/tubeup/TubeUp.py", line 359, in archive_urls
    identifier, meta = self.upload_ia(basename, custom_meta)
  File "/usr/local/lib/python3.7/site-packages/tubeup/TubeUp.py", line 273, in upload_ia
    with open(json_metadata_filepath) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/brandon/.tubeup/downloads/Stevie_Buckley_-_Managed_to_get_myself_blocked_on_LinkedIn_for_saying_that_this_is_the_best_parody_of_the_recruitment_industry_I_ve_ever_seen._Turns_out_Haigh_Associates_were_actually_being_sincere_with_this_video.-1051762443851112448.info.json'
```

Files in local tubeup cache (`.tubeup/downloads`):
```
Stevie_Buckley_-_Managed_to_get_myself_blocked_on_LinkedIn_for_saying_that_this_is_the_best_parody_of_the_recruitment_industry_I_ve_ever_seen._Turns_out_Haigh_Associates_were_actually_being_sincer...-1051762443851112448.annotations.xml
Stevie_Buckley_-_Managed_to_get_myself_blocked_on_LinkedIn_for_saying_that_this_is_the_best_parody_of_the_recruitment_industry_I_ve_ever_seen._Turns_out_Haigh_Associates_were_actually_being_sincer...-1051762443851112448.description
Stevie_Buckley_-_Managed_to_get_myself_blocked_on_LinkedIn_for_saying_that_this_is_the_best_parody_of_the_recruitment_industry_I_ve_ever_seen._Turns_out_Haigh_Associates_were_actually_being_sincer...-1051762443851112448.info.json
Stevie_Buckley_-_Managed_to_get_myself_blocked_on_LinkedIn_for_saying_that_this_is_the_best_parody_of_the_recruitment_industry_I_ve_ever_seen._Turns_out_Haigh_Associates_were_actually_being_sincer...-1051762443851112448.jpg
Stevie_Buckley_-_Managed_to_get_myself_blocked_on_LinkedIn_for_saying_that_this_is_the_best_parody_of_the_recruitment_industry_I_ve_ever_seen._Turns_out_Haigh_Associates_were_actually_being_sincer...-1051762443851112448.mp4
```

**Comment by brandongalbraith** [comment] 2018-10-16 17:40
Upon further analysis, it appears the issue is that the sanitization that *is* occurring is what's causing the "file not found" error. I intend to submit a PR with a proposed fix shortly.

**Comment by vxbinaca** [comment] 2018-10-16 23:31
@refeed does this sound correct to you?

**Comment by vxbinaca** [comment] 2018-10-16 23:33
Thanks for finding this.

**Comment by refeed** [comment] 2018-10-17 09:02
Ah yes, this is probably the problem that we've been searching for. Thanks @brandongalbraith !

P.S. probably related to #68

I'm hoping to work on this when I have a free time, otherwise, feel free to solve this issue, but please comment here first before working on this issue, so we can make sure that there's no 2 persons working on the same issue.

**Comment by vxbinaca** [comment] 2018-10-17 10:29
I have a reliable testing method to test a PR. Periscope videos.

**Comment by refeed** [comment] 2018-10-18 11:50
> I intend to submit a PR with a proposed fix shortly.

I didn't notice @brandongalbraith said this. Alright, thanks again. I'll assign this issue to @brandongalbraith  then

> I have a reliable testing method to test a PR. Periscope videos.

Yup, that's a good idea, and please test it with https://twitter.com/StevieBuckley/status/1051762443851112448 as well, since it's the main issue we're trying to fix here :)

**Comment by vxbinaca** [comment] 2018-12-03 08:05
@brandongalbraith  you might want to check out [#284](https://github.com/jjjake/internetarchive/issues/284) because this may be the cause. I'm semi-reliably failing on asian-script filenames.

**Comment by brandongalbraith** [comment] 2018-12-04 22:12
@vxbinaca Checked out https://github.com/jjjake/internetarchive/issues/284. PR inbound with item identifier used as filename for item files instead of attempting to sanitize/truncate filenames in a deterministic way with item descriptions:

Example: `Stevie_Buckley_-_Managed_to_get_myself_blocked_on_LinkedIn_for_saying_that_this_is_the_best_parody_of_the_recruitment_industry_I_ve_ever_seen._Turns_out_Haigh_Associates_were_actually_being_sincer...-1051762443851112448.info.json` becomes `twitter-1051762443851112448.info.json`

**Comment by vxbinaca** [comment] 2018-12-04 22:24
Do you feel this is strongly related to the problem of files just not uploading? In some cases yes it is but I sense it's multiple issues.

**Comment by vxbinaca** [comment] 2018-12-04 22:41
PR away. There won't be a conflict from the `*.xml` files, and for sure that won't be an issue in the future because annotations are being sunset.

My only issue is once we sleigh this dragon I have to look up the `videoID` to place left over videos in the proper collection - because there still be dragons even after your PR. Also Brandon, you're getting close to the threshold of bug fixes to where you deserve write access to the repo.

After you submit your PR I'm going to do one of my own, or two. Even though I have write to repo one of them is a license URL fix and I'd like your opinion on it.

**Comment by vxbinaca** [comment] 2018-12-04 22:45
Actually I already know what you need to do., It's in youtube-dls filename output. Just set it to be "`extractor`-`videoID`.*"

**Comment by brandongalbraith** [comment] 2018-12-07 21:02
This is a solid path to success I think. I'm testing locally now.

**Comment by vxbinaca** [comment] 2018-12-10 07:01
You're right on that last part. We'll keep filename output as-is. So the bug is somewhere else.

**Comment by brandongalbraith** [comment] 2018-12-10 15:06
Even though it isn't a fix for the asian script character issue, it does fix the issue of long item descriptions or descriptions that aren't compatible with local filesystem naming conventions ([which was my impetus for opening this issue](https://github.com/bibanon/tubeup/issues/73#issue-370704917)) causing tubeup to fail.

**Comment by vxbinaca** [comment] 2018-12-11 12:13
I'll test that later this week. The YTDL flag for cleansing non-ASCII is needed however due to IA not accepting spaces on upload and truncating the filenames.

After the dragons are sleighed I'm switching it to `extractor-videoID` simply for simplicity sake.After a rigorous test to see if it's stable and won't dump files but not upload.

**Comment by brandongalbraith** [comment] 2018-12-12 16:13
https://github.com/bibanon/tubeup/pull/81 closes this, @vxbinaca ship at your discretion. Thanks for allowing me to contribute and spending the time to discuss it!

**Closed** 2018-12-12 16:17 UTC

**Comment by vxbinaca** [comment] 2018-12-12 16:21
Anytime! As I'm not a programmer (skilled trades) I appreciate you explaining it to me like I'm 5.
