### ISSUE TITLE
TypeError: strptime() argument 1 must be str, not None

### ISSUE THREAD

**Issue by ohhdemgirls** [bibanon/tubeup#40] opened 2017-07-08 15:37 UTC
```
:: Uploading /root/.tubeup/downloads/Pong_AI_with_Policy_Gradients-YOW8m2YGtRg...
Traceback (most recent call last):
  File "/usr/local/bin/tubeup", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/tubeup/__main__.py", line 263, in main
    identifier, meta = upload_ia(video, custom_meta=md)
  File "/usr/local/lib/python3.5/dist-packages/tubeup/__main__.py", line 150, in upload_ia
    d = datetime.strptime(vid_meta['upload_date'], '%Y%m%d')
TypeError: strptime() argument 1 must be str, not None
```

**Comment by rudolphos** [comment] 2017-07-27 00:48
Same error here. I have the newest tubeup version.

```
:: Uploading ...
Traceback (most recent call last):
  File "/usr/local/bin/tubeup", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/tubeup/__main__.py", line 263, in main
    identifier, meta = upload_ia(video, custom_meta=md)
  File "/usr/local/lib/python3.5/dist-packages/tubeup/__main__.py", line 150, in upload_ia
    d = datetime.strptime(vid_meta['upload_date'], '%Y%m%d')
TypeError: strptime() argument 1 must be str, not None
```

**Comment by vxbinaca** [comment] 2017-07-27 03:58
Don't know what to say, let's home someone comes and fixes it.

**Comment by vxbinaca** [comment] 2017-07-27 06:42
@antonizoon any ideas? I'm about to start downgrading packages to see if it gets fixed.

**Comment by vxbinaca** [comment] 2017-07-27 08:07
So I'm conflicted and concerrned on this one. On one hand, this is random and difficult to reliably reproduce, although I have reproduced it. When I went back to push the video again, after removing it from the `.ytdlarchive' file and clearing the downloaded data, it started uploading again. This appears to be choking on item creation with regard to dates. But again, it's not reliably doing it.

My concern is for mine and DKL3's efforts at massive channel archival. The only way I would spot a problem is the steadily filling of the `~/.tubeup/downloads/` folder. You'd have to take the IDs from those files and clear them from your `.ytdlarchive` file, then do the rip again and it would probably pick up and attempt to upload those files again.

**Comment by antonizoon** [comment] 2017-07-27 16:25
If it's an issue of having no vid_date, wouldn't we just check if date is None, and use the current date if so?

**Comment by vxbinaca** [comment] 2017-07-27 20:36
@antonizoon Yes but we shouldn't be having this problem on YouTube, which provides the date.

**Comment by antonizoon** [comment] 2017-07-28 01:32
Then of course, we must find out exactly what kind of api data we are getting from YouTube...

**Comment by vxbinaca** [comment] 2017-07-28 22:55
Ant, it's not reproducing for me and I only ran into it once. So it's an inconsistent bug. Perhaps related to damaged packets?

@rudolphos and @ohhdemgirls you guys didn't give us the commands you ran. Also, remove that line with the video/song ID in your `.ytdlarchive` file, and delete everything in `~/.tubeup/downloads` director, and then re-rip the video.

I've been ingesting literally over 3000 YTPMV videos with 0 failures. I check the folder after a channel gets done ripping, no leftover files. I check the terminal output, no errors.

**Comment by vxbinaca** [comment] 2017-08-02 06:35
BTW guys, this is how you should be pasting these errors:

`tubeup https://www.youtube.com/watch\?v\=PjTm5TFuKUM`
`
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.07.23
[debug] Python version 3.4.5 - Linux-3.10.0-514.21.1.el7.x86_64-x86_64-with-centos-7.3.1611-Core
[debug] exe versions: none
[debug] Proxy map: {}
[debug] Public IP address: 52.175.214.202
{'elapsed': 0.28330445289611816, 'total_bytes': 982637, '_elapsed_str': '00:00', '_total_bytes_str': '959.61KiB', 'filename': '/home/vxbinaca/.tubeup/downloads/CM_OS_2-PjTm5TFuKUM.webm', 'downloaded_bytes': 982637, 'status': 'finished'}
:: Downloaded: /home/vxbinaca/.tubeup/downloads/CM_OS_2-PjTm5TFuKUM.webm...
:: Uploading /home/vxbinaca/.tubeup/downloads/CM_OS_2-PjTm5TFuKUM...
Traceback (most recent call last):
  File "/usr/bin/tubeup", line 9, in <module>
    load_entry_point('tubeup==0.0.6', 'console_scripts', 'tubeup')()
  File "/home/vxbinaca/.local/lib/python3.4/site-packages/tubeup/__main__.py", line 263, in main
    identifier, meta = upload_ia(video, custom_meta=md)
  File "/home/vxbinaca/.local/lib/python3.4/site-packages/tubeup/__main__.py", line 150, in upload_ia
    d = datetime.strptime(vid_meta['upload_date'], '%Y%m%d')
TypeError: must be str, not None
`

**Comment by vxbinaca** [comment] 2017-08-31 01:04
@antonizoon this error has become unberable, and I don't know if it's because the site changed but I can't rip any video. We either need to wait for Youtube-dl to update, or fix this. I'm leaning towards waiting first then once the new version is fixed do the 'fix'.

In the mean time I need to roll back a change before you change anything.

**Comment by vxbinaca** [comment] 2017-08-31 04:31
This was an error with youtube-dl, which a fix has been pushed on both our end and youtube-dls.

**Closed by vxbinaca** 2017-08-31 04:31 UTC
