### ISSUE TITLE
Don't slam info Json in command prompt by default

### ISSUE THREAD

**Issue by upintheairsheep** [bibanon/tubeup#201] opened 2022-05-21 21:48 UTC
It's annoying because I can't see the progress of the channel or playlist being downloaded. It also wastes RAM on low ram devices.

**Comment by vxbinaca** [comment] 2022-06-19 03:04
Are you channel ripping on a Raspberry Pi Nano?

**Comment by vxbinaca** [comment] 2022-06-19 03:04
Duplicate of #193 and it's being worked on, it's in our inbox.

**Closed by vxbinaca** 2022-06-19 03:04 UTC
