### ISSUE TITLE
Files are downloaded, but not uploaded

### ISSUE THREAD

**Issue by rudolphos** [bibanon/tubeup#61] opened 2017-12-03 23:27 UTC
Since the latest updates to tubeup archiving is not working for youtube channels or playlists, it only works for one URL at a time. Whole channel can't be archived, it downloads everything, but doesn't even start uploading. The same problem is also happening when trying to archive vid.me - tubeup downloads everything and doesn't upload. Also Periscope and facebook urls are having the same issue.

```
root@s:~# tubeup https://www.facebook.com/.../videos/.../
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.11.26
[debug] Python version 3.4.3 - Linux-3.4.0+-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.20-6, avprobe 9.20-6, ffmpeg 3.3.3, ffprobe 3.3.3
[debug] Proxy map: {}
[download] 100.0% of 150.66MiB at  4.01MiB/s ETA 00:00
{'downloaded_bytes': 157978090, 'filename': '../mnt/f/youtube/tubeup/downloads/....mp4', 'total_bytes': 157978090, '_total_bytes_str': '150.66MiB', '_elapsed_str': '00:37', 'elapsed': 37.57568573951721, 'status': 'finished'}
Downloaded ../mnt/f/youtube/tubeup/downloads/....mp4
[download] 100.0% of 19.91MiB at  2.60MiB/s ETA 00:00
{'downloaded_bytes': 20880946, 'filename': '../mnt/f/youtube/tubeup/downloads/....m4a', 'total_bytes': 20880946, '_total_bytes_str': '19.91MiB', '_elapsed_str': '00:07', 'elapsed': 7.6777238845825195, 'status': 'finished'}
Downloaded ../mnt/f/youtube/tubeup/downloads/....m4a

root@s:~# tubeup https://www.pscp.tv/w/...
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.11.26
[debug] Python version 3.4.3 - Linux-3.4.0+-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.20-6, avprobe 9.20-6, ffmpeg 3.3.3, ffprobe 3.3.3
[debug] Proxy map: {}
[download] 100.0% of ~66.01MiB at 746.25KiB/s ETA 00:00
{'total_bytes': 69218404, '_elapsed_str': '01:08', 'filename': '../mnt/f/youtube/tubeup/downloads/....mp4', '_total_bytes_str': '66MiB', 'elapsed': 68.55479526519775, 'downloaded_bytes': 69218404, 'status': 'finished'}
Downloaded ../mnt/f/youtube/tubeup/downloads/........mp4

root@s:~# tubeup https://www.pscp.tv/w/...
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.11.26
[debug] Python version 3.4.3 - Linux-3.4.0+-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.20-6, avprobe 9.20-6, ffmpeg 3.3.3, ffprobe 3.3.3
[debug] Proxy map: {}
root@s:~#
```

Just ran an update for components   `sudo -H pip3 install -U pip tubeup` but the problem is still occurring.

```
Downloaded ../mnt/f/youtube/tubeup/downloads/....mp4
root@s:~# tubeup https://www.pscp...
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.12.02
[debug] Python version 3.4.3 - Linux-3.4.0+-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.20-6, avprobe 9.20-6, ffmpeg 3.3.3, ffprobe 3.3.3
[debug] Proxy map: {}

{'filename': '../mnt/f/youtube/tubeup/downloads/....mp4', '_total_bytes_str': '66.01MiB', 'total_bytes': 69218404, 'status': 'finished'}
Downloaded ../mnt/f/youtube/tubeup/downloads/....mp4
root@s:~#
```

**Comment by refeed** [comment] 2017-12-04 02:36
Could you paste the output of using `--debug` argument when using tubeup for that url ?

**Comment by vxbinaca** [comment] 2017-12-04 08:32
Closing because it's a duplicate of #48 

@rudolphos I would advise against running tubeup as root.

**Comment by vxbinaca** [comment] 2018-01-22 09:26
Don't censor your URLs, periscope videos tend to vanish and we need the full URLs to test against.

```tubeup --debug facebook.com/yungestbae/videos/1661500077336192```

```
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.01.21
[debug] Python version 3.4.5 (CPython) - Linux-3.10.0-693.11.6.el7.x86_64-x86_64-with-centos-7.4.1708-Core
[debug] exe versions: none
[debug] Proxy map: {}
[DEBUG] 2018-01-22 09:17:33,756 - tubeup.TubeUp - WARNING - The url doesn't specify the protocol, trying with http
[DEBUG] 2018-01-22 09:17:33,758 - tubeup.TubeUp - DEBUG - [facebook] 1661500077336192: Downloading webpage
[DEBUG] 2018-01-22 09:17:34,737 - tubeup.TubeUp - DEBUG - [debug] Default format spec: best/bestvideo+bestaudio
[DEBUG] 2018-01-22 09:17:34,799 - tubeup.TubeUp - DEBUG - Kendrick Lamar - DNA. (Yung Bae Remix)  January 29th.
[DEBUG] 2018-01-22 09:17:34,800 - tubeup.TubeUp - DEBUG - {"extractor": "facebook", "ext": "mp4", "playlist": null, "url": "https://video-sin6-1.xx.fbcdn.net/v/t43.1792-2/10000000_2057011104545125_6954688693844049920_n.mp4?efg=eyJ2ZW5jb2RlX3RhZyI6InN2ZV9oZCJ9&oh=3eda8cd484d2b7b6b46cb45105f652b6&oe=5A65EA52", "timestamp": 1515897977, "thumbnails": [{"id": "0", "url": "https://scontent-sin6-1.xx.fbcdn.net/v/t15.0-10/24587226_1661500620669471_5404051211877875712_n.jpg?oh=478b54b3005798043d121150ed47787e&oe=5AF4AEC4"}], "display_id": "1661500077336192", "fulltitle": "Kendrick Lamar - DNA. (Yung Bae Remix)  January 29th.", "format": "dash_hd_src_no_ratelimit - unknown", "format_id": "dash_hd_src_no_ratelimit", "playlist_index": null, "id": "1661500077336192", "webpage_url_basename": "1661500077336192", "webpage_url": "http://facebook.com/yungestbae/videos/1661500077336192", "preference": 5, "upload_date": "20180114", "http_headers": {"Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "Accept-Charset": "ISO-8859-1,utf-8;q=0.7,*;q=0.7", "Accept-Encoding": "gzip, deflate", "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0 (Chrome)", "Accept-Language": "en-us,en;q=0.5"}, "protocol": "https", "extractor_key": "Facebook", "uploader": "YUNG BAE", "thumbnail": "https://scontent-sin6-1.xx.fbcdn.net/v/t15.0-10/24587226_1661500620669471_5404051211877875712_n.jpg?oh=478b54b3005798043d121150ed47787e&oe=5AF4AEC4", "requested_subtitles": null, "formats": [{"height": null, "ext": "m4a", "width": null, "http_headers": {"Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "Accept-Charset": "ISO-8859-1,utf-8;q=0.7,*;q=0.7", "Accept-Encoding": "gzip, deflate", "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0 (Chrome)", "Accept-Language": "en-us,en;q=0.5"}, "format_note": "DASH audio", "language": "eng", "url": "https://video-sin6-1.xx.fbcdn.net/v/t42.1790-2/26889374_2110979615788252_7826805717674754048_n.mp4?efg=eyJ2ZW5jb2RlX3RhZyI6ImRhc2hfdjNfNDI2X2NyZl8yM19tYWluXzMuMF9mcmFnXzJfYXVkaW8ifQ==&oh=e98e309a0ee2ac20f0242fe4a128b1a6&oe=5A65EBB3", "asr": 48000, "vcodec": "none", "manifest_url": null, "fps": null, "acodec": "mp4a.40.5", "tbr": 49.343, "format_id": "2110979612454919ad", "filesize": null, "format": "2110979612454919ad - audio only (DASH audio)", "protocol": "https", "container": "m4a_dash"}, {"height": 144, "ext": "mp4", "width": 256, "http_headers": {"Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "Accept-Charset": "ISO-8859-1,utf-8;q=0.7,*;q=0.7", "Accept-Encoding": "gzip, deflate", "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0 (Chrome)", "Accept-Language": "en-us,en;q=0.5"}, "format_note": "DASH video", "language": null, "url": "https://video-sin6-1.xx.fbcdn.net/v/t42.1790-2/26813209_155065821812870_7223188333835321344_n.mp4?efg=eyJ2ZW5jb2RlX3RhZyI6ImRhc2hfdjNfMjU2X2NyZl8yM19tYWluXzMuMF9mcmFnXzJfdmlkZW8ifQ==&oh=10ae4de068f0af5bdabde8d73de5a4f2&oe=5A65EB31", "asr": null, "vcodec": "avc1.4d401e", "manifest_url": null, "fps": 25, "acodec": "none", "tbr": 248.642, "format_id": "155065818479537v", "filesize": null, "format": "155065818479537v - 256x144 (DASH video)", "protocol": "https", "container": "mp4_dash"}, {"height": 270, "ext": "mp4", "width": 480, "http_headers": {"Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "Accept-Charset": "ISO-8859-1,utf-8;q=0.7,*;q=0.7", "Accept-Encoding": "gzip, deflate", "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0 (Chrome)", "Accept-Language": "en-us,en;q=0.5"}, "format_note": "DASH video", "language": null, "url": "https://video-sin6-1.xx.fbcdn.net/v/t42.1790-2/26846157_2096515427260790_1326988398740635648_n.mp4?efg=eyJ2ZW5jb2RlX3RhZyI6ImRhc2hfdjRfaHEzX2ZyYWdfMl92aWRlbyJ9&oh=869b06baf05d37d88f51614fc27c38d3&oe=5A65DB73", "asr": null, "vcodec": "avc1.4d401e", "manifest_url": null, "fps": 25, "acodec": "none", "tbr": 461.13, "format_id": "2096515423927457vd", "filesize": null, "format": "2096515423927457vd - 480x270 (DASH video)", "protocol": "https", "container": "mp4_dash"}, {"height": 360, "ext": "mp4", "width": 640, "http_headers": {"Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "Accept-Charset": "ISO-8859-1,utf-8;q=0.7,*;q=0.7", "Accept-Encoding": "gzip, deflate", "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0 (Chrome)", "Accept-Language": "en-us,en;q=0.5"}, "format_note": "DASH video", "language": null, "url": "https://video-sin6-1.xx.fbcdn.net/v/t42.1790-2/26832727_1914766028553546_1271954130918703104_n.mp4?efg=eyJ2ZW5jb2RlX3RhZyI6ImRhc2hfdjNfNjQwX2NyZl8yM19tYWluXzMuMF9mcmFnXzJfdmlkZW8ifQ==&oh=e9c2b690b8b0b343b97d6215f2123ff4&oe=5A65DB3E", "asr": null, "vcodec": "avc1.4d401e", "manifest_url": null, "fps": 25, "acodec": "none", "tbr": 817.721, "format_id": "1914766021886880v", "filesize": null, "format": "1914766021886880v - 640x360 (DASH video)", "protocol": "https", "container": "mp4_dash"}, {"height": 480, "ext": "mp4", "width": 854, "http_headers": {"Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "Accept-Charset": "ISO-8859-1,utf-8;q=0.7,*;q=0.7", "Accept-Encoding": "gzip, deflate", "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0 (Chrome)", "Accept-Language": "en-us,en;q=0.5"}, "format_note": "DASH video", "language": null, "url": "https://video-sin6-1.xx.fbcdn.net/v/t42.1790-2/26805792_204784600091082_443179430253166592_n.mp4?efg=eyJ2ZW5jb2RlX3RhZyI6ImRhc2hfdjNfODU0X2NyZl8yM19tYWluXzMuMF9mcmFnXzJfdmlkZW8ifQ==&oh=cf0d4b2b93bd1acd7283ec3c54399a74&oe=5A65D844", "asr": null, "vcodec": "avc1.4d401e", "manifest_url": null, "fps": 25, "acodec": "none", "tbr": 1196.336, "format_id": "204784596757749v", "filesize": null, "format": "204784596757749v - 854x480 (DASH video)", "protocol": "https", "container": "mp4_dash"}, {"height": 720, "ext": "mp4", "width": 1280, "http_headers": {"Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "Accept-Charset": "ISO-8859-1,utf-8;q=0.7,*;q=0.7", "Accept-Encoding": "gzip, deflate", "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0 (Chrome)", "Accept-Language": "en-us,en;q=0.5"}, "format_note": "DASH video", "language": null, "url": "https://video-sin6-1.xx.fbcdn.net/v/t42.1790-2/10000000_538145163231004_9095680056394514432_n.mp4?efg=eyJ2ZW5jb2RlX3RhZyI6ImRhc2hfdjRfaHEyX2ZyYWdfMl92aWRlbyJ9&oh=170314caf63420bb479a9c16565eca0a&oe=5A65D7D8", "asr": null, "vcodec": "avc1.4d401f", "manifest_url": null, "fps": 25, "acodec": "none", "tbr": 1789.738, "format_id": "538145149897672v", "filesize": null, "format": "538145149897672v - 1280x720 (DASH video)", "protocol": "https", "container": "mp4_dash"}, {"preference": 0, "ext": "mp4", "http_headers": {"Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "Accept-Charset": "ISO-8859-1,utf-8;q=0.7,*;q=0.7", "Accept-Encoding": "gzip, deflate", "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0 (Chrome)", "Accept-Language": "en-us,en;q=0.5"}, "format_id": "dash_sd_src", "protocol": "https", "url": "https://video-sin6-1.xx.fbcdn.net/v/t42.1790-2/26836684_171015156840942_3659553143986847744_n.mp4?efg=eyJybHIiOjg4MywicmxhIjo1MTQsInZlbmNvZGVfdGFnIjoic3ZlX3NkIn0%3D&rl=883&vabr=491&oh=478d92d65203463cd8d70a3603e11000&oe=5A65D8D8", "format": "dash_sd_src - unknown"}, {"preference": 0, "ext": "mp4", "http_headers": {"Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "Accept-Charset": "ISO-8859-1,utf-8;q=0.7,*;q=0.7", "Accept-Encoding": "gzip, deflate", "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0 (Chrome)", "Accept-Language": "en-us,en;q=0.5"}, "format_id": "dash_sd_src_no_ratelimit", "protocol": "https", "url": "https://video-sin6-1.xx.fbcdn.net/v/t42.1790-2/26836684_171015156840942_3659553143986847744_n.mp4?efg=eyJ2ZW5jb2RlX3RhZyI6InN2ZV9zZCJ9&oh=478d92d65203463cd8d70a3603e11000&oe=5A65D8D8", "format": "dash_sd_src_no_ratelimit - unknown"}, {"preference": 5, "ext": "mp4", "http_headers": {"Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "Accept-Charset": "ISO-8859-1,utf-8;q=0.7,*;q=0.7", "Accept-Encoding": "gzip, deflate", "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0 (Chrome)", "Accept-Language": "en-us,en;q=0.5"}, "format_id": "dash_hd_src", "protocol": "https", "url": "https://video-sin6-1.xx.fbcdn.net/v/t43.1792-2/10000000_2057011104545125_6954688693844049920_n.mp4?efg=eyJybHIiOjMyOTUsInJsYSI6MjMwMSwidmVuY29kZV90YWciOiJzdmVfaGQifQ%3D%3D&rl=3295&vabr=2197&oh=3eda8cd484d2b7b6b46cb45105f652b6&oe=5A65EA52", "format": "dash_hd_src - unknown"}, {"preference": 5, "ext": "mp4", "http_headers": {"Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "Accept-Charset": "ISO-8859-1,utf-8;q=0.7,*;q=0.7", "Accept-Encoding": "gzip, deflate", "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0 (Chrome)", "Accept-Language": "en-us,en;q=0.5"}, "format_id": "dash_hd_src_no_ratelimit", "protocol": "https", "url": "https://video-sin6-1.xx.fbcdn.net/v/t43.1792-2/10000000_2057011104545125_6954688693844049920_n.mp4?efg=eyJ2ZW5jb2RlX3RhZyI6InN2ZV9oZCJ9&oh=3eda8cd484d2b7b6b46cb45105f652b6&oe=5A65EA52", "format": "dash_hd_src_no_ratelimit - unknown"}], "_filename": "/home/vxbinaca/.tubeup/downloads/Kendrick_Lamar_-_DNA._Yung_Bae_Remix_January_29th.-1661500077336192.mp4", "title": "Kendrick Lamar - DNA. (Yung Bae Remix)  January 29th."}
[DEBUG] 2018-01-22 09:17:34,800 - tubeup.TubeUp - WARNING - There's no description to write.
[DEBUG] 2018-01-22 09:17:34,800 - tubeup.TubeUp - DEBUG - [info] Writing video annotations to: /home/vxbinaca/.tubeup/downloads/Kendrick_Lamar_-_DNA._Yung_Bae_Remix_January_29th.-1661500077336192.annotations.xml
[DEBUG] 2018-01-22 09:17:34,800 - tubeup.TubeUp - WARNING - There are no annotations to write.
[DEBUG] 2018-01-22 09:17:34,800 - tubeup.TubeUp - DEBUG - [info] Writing video description metadata as JSON to: /home/vxbinaca/.tubeup/downloads/Kendrick_Lamar_-_DNA._Yung_Bae_Remix_January_29th.-1661500077336192.info.json
[DEBUG] 2018-01-22 09:17:34,802 - tubeup.TubeUp - DEBUG - [facebook] 1661500077336192: Downloading thumbnail ...
[DEBUG] 2018-01-22 09:17:36,252 - tubeup.TubeUp - DEBUG - [facebook] 1661500077336192: Writing thumbnail to: /home/vxbinaca/.tubeup/downloads/Kendrick_Lamar_-_DNA._Yung_Bae_Remix_January_29th.-1661500077336192.jpg
[DEBUG] 2018-01-22 09:17:36,252 - tubeup.TubeUp - DEBUG - [debug] Invoking downloader on 'https://video-sin6-1.xx.fbcdn.net/v/t43.1792-2/10000000_2057011104545125_6954688693844049920_n.mp4?efg=eyJ2ZW5jb2RlX3RhZyI6InN2ZV9oZCJ9&oh=3eda8cd484d2b7b6b46cb45105f652b6&oe=5A65EA52'
[DEBUG] 2018-01-22 09:17:37,238 - tubeup.TubeUp - DEBUG - [download] Destination: /home/vxbinaca/.tubeup/downloads/Kendrick_Lamar_-_DNA._Yung_Bae_Remix_January_29th.-1661500077336192.mp4
[DEBUG] 2018-01-22 09:17:37,238 - tubeup.TubeUp - DEBUG - [download]   0.0% of 14.63MiB at Unknown speed ETA Unknown ETA
[download]   0.0% of 14.63MiB at Unknown speed ETA Unknown ETA[DEBUG] 2018-01-22 09:17:37,238 - tubeup.TubeUp - DEBUG - [download]   0.0% of 14.63MiB at Unknown speed ETA Unknown ETA
[download]   0.0% of 14.63MiB at Unknown speed ETA Unknown ETA[DEBUG] 2018-01-22 09:17:37,239 - tubeup.TubeUp - DEBUG - [download]   0.0% of 14.63MiB at  5.68MiB/s ETA 00:02
[download]   0.0% of 14.63MiB at  5.68MiB/s ETA 00:02[DEBUG] 2018-01-22 09:17:37,481 - tubeup.TubeUp - DEBUG - [download]   0.1% of 14.63MiB at 61.71KiB/s ETA 04:02
[download]   0.1% of 14.63MiB at 61.71KiB/s ETA 04:02[DEBUG] 2018-01-22 09:17:37,496 - tubeup.TubeUp - DEBUG - [download]   0.2% of 14.63MiB at 119.94KiB/s ETA 02:04
[download]   0.2% of 14.63MiB at 119.94KiB/s ETA 02:04[DEBUG] 2018-01-22 09:17:37,782 - tubeup.TubeUp - DEBUG - [download]   0.4% of 14.63MiB at 115.66KiB/s ETA 02:09
[download]   0.4% of 14.63MiB at 115.66KiB/s ETA 02:09[DEBUG] 2018-01-22 09:17:38,028 - tubeup.TubeUp - DEBUG - [download]   0.8% of 14.63MiB at 160.67KiB/s ETA 01:32
[download]   0.8% of 14.63MiB at 160.67KiB/s ETA 01:32[DEBUG] 2018-01-22 09:17:38,265 - tubeup.TubeUp - DEBUG - [download]   1.7% of 14.63MiB at 248.22KiB/s ETA 00:59
[download]   1.7% of 14.63MiB at 248.22KiB/s ETA 00:59[DEBUG] 2018-01-22 09:17:38,507 - tubeup.TubeUp - DEBUG - [download]   3.4% of 14.63MiB at 402.61KiB/s ETA 00:35
[download]   3.4% of 14.63MiB at 402.61KiB/s ETA 00:35[DEBUG] 2018-01-22 09:17:38,743 - tubeup.TubeUp - DEBUG - [download]   6.8% of 14.63MiB at 679.30KiB/s ETA 00:20
[download]   6.8% of 14.63MiB at 679.30KiB/s ETA 00:20[DEBUG] 2018-01-22 09:17:38,986 - tubeup.TubeUp - DEBUG - [download]  13.7% of 14.63MiB at  1.14MiB/s ETA 00:11
[download]  13.7% of 14.63MiB at  1.14MiB/s ETA 00:11[DEBUG] 2018-01-22 09:17:39,232 - tubeup.TubeUp - DEBUG - [download]  27.3% of 14.63MiB at  2.01MiB/s ETA 00:05
[download]  27.3% of 14.63MiB at  2.01MiB/s ETA 00:05[DEBUG] 2018-01-22 09:17:39,546 - tubeup.TubeUp - DEBUG - [download]  54.7% of 14.63MiB at  3.47MiB/s ETA 00:01
[download]  54.7% of 14.63MiB at  3.47MiB/s ETA 00:01[DEBUG] 2018-01-22 09:17:39,836 - tubeup.TubeUp - DEBUG - [download]  82.0% of 14.63MiB at  4.62MiB/s ETA 00:00
[download]  82.0% of 14.63MiB at  4.62MiB/s ETA 00:00[DEBUG] 2018-01-22 09:17:40,061 - tubeup.TubeUp - DEBUG - [download] 100.0% of 14.63MiB at  5.18MiB/s ETA 00:00
[download] 100.0% of 14.63MiB at  5.18MiB/s ETA 00:00[DEBUG] 2018-01-22 09:17:40,062 - tubeup.TubeUp - DEBUG - [download] 100% of 14.63MiB in 00:02
[DEBUG] 2018-01-22 09:17:40,063 - tubeup.TubeUp - DEBUG - {'filename': '/home/vxbinaca/.tubeup/downloads/Kendrick_Lamar_-_DNA._Yung_Bae_Remix_January_29th.-1661500077336192.mp4', 'elapsed': 2.8250250816345215, 'total_bytes': 15345076, '_total_bytes_str': '14.63MiB', '_elapsed_str': '00:02', 'status': 'finished', 'downloaded_bytes': 15345076}
[DEBUG] 2018-01-22 09:17:40,063 - tubeup.TubeUp - INFO - Downloaded /home/vxbinaca/.tubeup/downloads/Kendrick_Lamar_-_DNA._Yung_Bae_Remix_January_29th.-1661500077336192.mp4

{'filename': '/home/vxbinaca/.tubeup/downloads/Kendrick_Lamar_-_DNA._Yung_Bae_Remix_January_29th.-1661500077336192.mp4', 'elapsed': 2.8250250816345215, 'total_bytes': 15345076, '_total_bytes_str': '14.63MiB', '_elapsed_str': '00:02', 'status': 'finished', 'downloaded_bytes': 15345076}
Downloaded /home/vxbinaca/.tubeup/downloads/Kendrick_Lamar_-_DNA._Yung_Bae_Remix_January_29th.-1661500077336192.mp4
[DEBUG] 2018-01-22 09:17:40,063 - tubeup.TubeUp - DEBUG - Creating basenames from ydl info dict with type video
[DEBUG] 2018-01-22 09:17:40,066 - tubeup.TubeUp - DEBUG - Basenames obtained from url (facebook.com/yungestbae/videos/1661500077336192): {'/home/vxbinaca/.tubeup/downloads/Kendrick_Lamar_-_DNA._Yung_Bae_Remix_January_29th.-1661500077336192'}
```

Whatever Tubeup does inbetween youtube-dl finishing downloads and internetarchive doing uploads, thats's where it's dying.

If we slay this dragon most of the issues Tubeup had vanishes.

I also think this issue is in one of the dependencies of tubeup. We might be able to nip it in the bud by force-reverting the dependency to a version not affected. Also @refeed is right we should lock down specific versions of dependencies from now on.

**Comment by brandongalbraith** [comment] 2018-03-01 17:17
Based on a tubeup run I executed today, this might be caused by the annotations.xml file being 0 bytes. Will provide an update after further testing.

**Comment by vxbinaca** [comment] 2018-03-01 19:24
@brandongalbraith I think it's JSON based because it does it sometimes for Youtube but always for Periscope and Facebook. Fails every time. I just don't know what's causing it.

**Comment by rudolphos** [comment] 2018-04-14 14:59
This happens on channels/playlists that have more than ~40+ videos, I've tried channels with 12 videos and it was successful. Probably because there's more probability that there's something wrong with json between larger number of files. Or as @brandongalbraith said annotations.xml being 0 bytes.

**Comment by refeed** [comment] 2018-04-18 11:46
hmm, interesting. Could anyone give me a link to a sample channel? so I can test it in my environment

**Closed** 2018-09-12 00:37 UTC

**Comment by rudolphos** [comment] 2018-09-20 17:54
I updated tubeup and this happened again when archiving channel with 5-10 videos. When archiving individually youtube urls, it works.

sudo tubeup https://www.youtube.com/channel/... --use-download-archive
...
```
[download] 100.0% of 126.75MiB at 10.57MiB/s ETA 00:00
{'filename': '/home/user/.tubeup/downloads/....f136.mp4', 'status': 'finished', 'total_bytes': 132912230, 'downloaded_bytes': 132912230, 'elapsed': 13.876163721084595, '_total_bytes_str': '126.75MiB', '_elapsed_str': '00:13'}
Downloaded /home/user/.tubeup/downloads/...f136.mp4
[download] 100.0% of 15.47MiB at 10.35MiB/s ETA 00:00
{'filename': '/home/user/.tubeup/downloads/...f251.webm', 'status': 'finished', 'total_bytes': 16221540, 'downloaded_bytes': 16221540, 'elapsed': 1.5162699222564697, '_total_bytes_str': '15.47MiB', '_elapsed_str': '00:01'}
Downloaded /home/user/.tubeup/downloads/....f251.webm

An exception just occured, if you found this exception isn't related with any of your connection problem, please report this issue to https://github.com/bibanon/tubeup/issues
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tubeup/__main__.py", line 91, in main
    use_download_archive):
  File "/usr/local/lib/python3.5/dist-packages/tubeup/TubeUp.py", line 356, in archive_urls
    urls, proxy, ydl_username, ydl_password, use_download_archive)
  File "/usr/local/lib/python3.5/dist-packages/tubeup/TubeUp.py", line 144, in get_resource_basenames
    self.create_basenames_from_ydl_info_dict(ydl, info_dict)
  File "/usr/local/lib/python3.5/dist-packages/tubeup/TubeUp.py", line 172, in create_basenames_from_ydl_info_dict
    filenames.add(ydl.prepare_filename(video))
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/YoutubeDL.py", line 632, in prepare_filename
    template_dict = dict(info_dict)
TypeError: 'NoneType' object is not iterable

```

**Comment by rudolphos** [comment] 2018-09-20 18:32
I updated tubeup and this happened again when archiving channel with 5-10 videos. When archiving individually youtube urls, it works.

```
sudo tubeup https://www.youtube.com/channel/... --use-download-archive
...

[download] 100.0% of 126.75MiB at 10.57MiB/s ETA 00:00
{'filename': '/home/user/.tubeup/downloads/....f136.mp4', 'status': 'finished', 'total_bytes': 132912230, 'downloaded_bytes': 132912230, 'elapsed': 13.876163721084595, '_total_bytes_str': '126.75MiB', '_elapsed_str': '00:13'}
Downloaded /home/user/.tubeup/downloads/...f136.mp4
[download] 100.0% of 15.47MiB at 10.35MiB/s ETA 00:00
{'filename': '/home/user/.tubeup/downloads/...f251.webm', 'status': 'finished', 'total_bytes': 16221540, 'downloaded_bytes': 16221540, 'elapsed': 1.5162699222564697, '_total_bytes_str': '15.47MiB', '_elapsed_str': '00:01'}
Downloaded /home/user/.tubeup/downloads/....f251.webm

An exception just occured, if you found this exception isn't related with any of your connection problem, please report this issue to https://github.com/bibanon/tubeup/issues
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tubeup/__main__.py", line 91, in main
    use_download_archive):
  File "/usr/local/lib/python3.5/dist-packages/tubeup/TubeUp.py", line 356, in archive_urls
    urls, proxy, ydl_username, ydl_password, use_download_archive)
  File "/usr/local/lib/python3.5/dist-packages/tubeup/TubeUp.py", line 144, in get_resource_basenames
    self.create_basenames_from_ydl_info_dict(ydl, info_dict)
  File "/usr/local/lib/python3.5/dist-packages/tubeup/TubeUp.py", line 172, in create_basenames_from_ydl_info_dict
    filenames.add(ydl.prepare_filename(video))
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/YoutubeDL.py", line 632, in prepare_filename
    template_dict = dict(info_dict)
TypeError: 'NoneType' object is not iterable

```

**Comment by vxbinaca** [comment] 2018-09-20 21:31
@rudolphos Fow now where's what you do:

use youtube-dl to print out the IDs which is `--get-id'

Then create commands for each video ID, that's the safest way.

Also this isn't realted to the lat bug. So Make a issue next time.

**Comment by DuckHP** [comment] 2018-12-27 16:15
> Don't censor your URLs, periscope videos tend to vanish and we need the full URLs to test against.
> 
> `tubeup --debug facebook.com/yungestbae/videos/1661500077336192`
> 

https://archive.org/details/facebook-1661500077336192 ..couldn't help myself :100:
