### ISSUE TITLE
Tubeup error

### ISSUE THREAD

**Issue by vxbinaca** [bibanon/tubeup#68] opened 2018-09-20 21:37 UTC
```
An exception just occured, if you found this exception isn't related with any of your connection problem, please report this issue to https://github.com/bibanon/tubeup/issues
Traceback (most recent call last):
  File "/home/vxbinaca/.local/lib/python3.4/site-packages/tubeup/__main__.py", line 91, in main
    use_download_archive):
  File "/home/vxbinaca/.local/lib/python3.4/site-packages/tubeup/TubeUp.py", line 356, in archive_urls
    urls, proxy, ydl_username, ydl_password, use_download_archive)
  File "/home/vxbinaca/.local/lib/python3.4/site-packages/tubeup/TubeUp.py", line 144, in get_resource_basenames
    self.create_basenames_from_ydl_info_dict(ydl, info_dict)
  File "/home/vxbinaca/.local/lib/python3.4/site-packages/tubeup/TubeUp.py", line 172, in create_basenames_from_ydl_info_dict
    filenames.add(ydl.prepare_filename(video))
  File "/home/vxbinaca/.local/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 632, in prepare_filename
    template_dict = dict(info_dict)
TypeError: 'NoneType' object is not iterable
```

Edited by @refeed :
More info in https://github.com/bibanon/tubeup/issues/61#issuecomment-423287622
> I updated tubeup and this happened again when archiving channel with 5-10 videos. When archiving individually youtube urls, it works.

**Comment by refeed** [comment] 2018-09-29 03:29
@rudolphos Could you help us by giving an URL to reproduce this issue?

**Comment by vxbinaca** [comment] 2018-09-29 22:00
It seems like a JSON error:

`tubeup --use-download-archive --metadata=collection:weedtubers https://www.periscope.tv/CoureyPie/1vAGRRqZVDyGl`

```
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.09.26
[debug] Python version 3.4.9 (CPython) - Linux-4.15.18-1-pve-x86_64-with-centos-7.5.1804-Core
[debug] exe versions: ffmpeg 2.8.15, ffprobe 2.8.15
[debug] Proxy map: {}

An exception just occured, if you found this exception isn't related with any of your connection problem, please report this issue to https://github.com/bibanon/tubeup/issues
Traceback (most recent call last):
  File "/home/vxbinaca/.local/lib/python3.4/site-packages/tubeup/__main__.py", line 91, in main
    use_download_archive):
  File "/home/vxbinaca/.local/lib/python3.4/site-packages/tubeup/TubeUp.py", line 359, in archive_urls
    identifier, meta = self.upload_ia(basename, custom_meta)
  File "/home/vxbinaca/.local/lib/python3.4/site-packages/tubeup/TubeUp.py", line 273, in upload_ia
    with open(json_metadata_filepath) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/vxbinaca/.tubeup/downloads/Courey_-_Smoke_throwback_jams_hotboxtheinternet_420_stonergirls-1vAGRRqZVDyGl.info.json'
```

@rudolphos I'm going to make issue submission guidelines because of you. They'll require submission of the command you used with URL so we can test, and you'll have to use Github markup like I did in this post. Failure to either one of these will result in closure of the issue. We don't care that you back up right-wing content. Don't try to hide the URL from us we need it to fix the script.

**Comment by rudolphos** [comment] 2018-10-06 11:39
@vxbinaca I don't remember which channel it was, but it's possible it happens when some channels have videos put in limited state or geoblocked, I don't really know. That particular channel had a few videos in limited state+geoblocked.

**Comment by vxbinaca** [comment] 2018-10-07 08:41
@rudolphos No, you can hit the Up key and look at the last commands you ran. Limited state videos still show when you dump a channels IDs, geoblocked throw up an error when you try to rip them but still show.

`tubeup --use-download-archive --metadata=collection:tubeup Z-nLNHzsAD8`
```
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.10.05
[debug] Python version 3.4.9 (CPython) - Linux-4.15.18-1-pve-x86_64-with-centos-7.5.1804-Core
[debug] exe versions: ffmpeg 2.8.15, ffprobe 2.8.15
[debug] Proxy map: {}
video doesn't have subtitles

An exception just occured, if you found this exception isn't related with any of your connection problem, please report this issue to https://github.com/bibanon/tubeup/issues
Traceback (most recent call last):
  File "/home/vxbinaca/.local/lib/python3.4/site-packages/tubeup/__main__.py", line 91, in main
    use_download_archive):
  File "/home/vxbinaca/.local/lib/python3.4/site-packages/tubeup/TubeUp.py", line 359, in archive_urls
    identifier, meta = self.upload_ia(basename, custom_meta)
  File "/home/vxbinaca/.local/lib/python3.4/site-packages/tubeup/TubeUp.py", line 273, in upload_ia
    with open(json_metadata_filepath) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/vxbinaca/.tubeup/downloads/le_monke_full_rap-Z-nLNHzsAD8.info.json'
```

Tubeup is wonky right now due to:

- File parsing errors because Tubeup needs to be gone through with a fine tooth comb.
- JSON errors that just make a video at random not upload and leaves the downloaded result in the .tubeup folder.

**Comment by refeed** [comment] 2018-10-09 00:13
About the `.info.json` missing issue, I think it's an intermittent issue produced by youtube-dl, I still can't reproduce it until now. https://pastebin.com/DB69PNyS

We do can make a code to re-run `youtube-dl` until we get the `.info.json` file which is crucial for ia metadata

**Comment by vxbinaca** [comment] 2018-10-09 03:33
I've rerun it multiple times same result.

**Comment by refeed** [comment] 2018-10-09 03:55
@vxbinaca Could you try to download a video from youtube with `youtube-dl`
with `--write-info-json`  and `--verbose` and paste the result here?

Pada tanggal Sel, 9 Okt 2018 pukul 10.33 Paul Henning <
notifications@github.com> menulis:

**Comment by vxbinaca** [comment] 2018-10-09 03:56
Yeah gimme a bit

**Comment by ealgase** [comment] 2019-05-31 02:40
Any update?  Also having this issue with https://www.youtube.com/user/sthetix360

**Comment by vxbinaca** [comment] 2019-05-31 02:47
@ealgase use youtube-dl to output the channels videoIDs then have tubeup rip each video individually.

**Comment by ealgase** [comment] 2019-05-31 03:18
OK.

**Comment by vxbinaca** [comment] 2019-06-04 02:33
@refeed here's the symptoms that trigger upload failures for some youtube channels:

- A copyrighted video or deleted video will kill the channel rip on download. We should be able to gracefully handle this better despite that we're using `--ignore-errors` and it not working. Even if you complete a channel rip AROUND the errored video, it will still kill future updates when when using `--use-download-archive`. It will see the bad ID and kill the rip. 

- Sometimes randomly the hand off between a completed rip and upload fails. This particular problem started when you switched us to OOP. So this is your bug that would be nice to see fixed before your vanish for another year.


In the interim I'm going up add a warning about ripping entire channels.

**Comment by brandongalbraith** [comment] 2021-09-30 19:32
I believe this issue is fixed with the move to the new yt-dlp extractor. Please reopen if issues reoccurs with the latest version of tubeup. Thanks!

**Closed by brandongalbraith** 2021-09-30 19:32 UTC
