### ISSUE TITLE
Facebook Uploading Issue

### ISSUE THREAD

**Issue by dkl3** [bibanon/tubeup#48] opened 2017-10-06 05:10 UTC
$ tubeup  https://www.facebook.com/GreenDay/videos/10154561156789521/

[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.10.01
[debug] Python version 3.5.2 - Linux-4.10.0-35-generic-i686-with-LinuxMint-18.2-sonya
[debug] exe versions: ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1
[debug] Proxy map: {}
[debug] Public IP address: 2601:600:9880:390:818a:d092:d4b2:18e
{'status': 'finished', 'downloaded_bytes': 38679766, '_elapsed_str': '00:06', 'total_bytes': 38679766, '_total_bytes_str': '36.89MiB', 'elapsed': 6.104719877243042, 'filename': '/home/USER/.tubeup/downloads/Green_Day_s_Bang_Bang_Video_Directed_By_Tim_Armstrong._Here_s_A_Behind_Th...-10154561156789521.f10154561198149521v.mp4'}
:: Downloaded: /home/USER/.tubeup/downloads/Green_Day_s_Bang_Bang_Video_Directed_By_Tim_Armstrong._Here_s_A_Behind_Th...-10154561156789521.f10154561198149521v.mp4...
{'status': 'finished', 'downloaded_bytes': 674879, '_elapsed_str': '00:00', 'total_bytes': 674879, '_total_bytes_str': '659.06KiB', 'elapsed': 0.5873575210571289, 'filename': '/home/USER/.tubeup/downloads/Green_Day_s_Bang_Bang_Video_Directed_By_Tim_Armstrong._Here_s_A_Behind_Th...-10154561156789521.f10154561191199521ad.m4a'}
:: Downloaded: /home/USER/.tubeup/downloads/Green_Day_s_Bang_Bang_Video_Directed_By_Tim_Armstrong._Here_s_A_Behind_Th...-10154561156789521.f10154561191199521ad.m4a...
:: Uploading /home/USER/.tubeup/downloads/Green_Day_s_Bang_Bang_Video_Directed_By_Tim_Armstrong._Here_s_A_Behind_Th...-10154561156789521v...
Traceback (most recent call last):
  File "/usr/local/bin/tubeup", line 9, in <module>
    load_entry_point('tubeup==0.0.11', 'console_scripts', 'tubeup')()
  File "/usr/local/lib/python3.5/dist-packages/tubeup/__main__.py", line 298, in main
    identifier, meta = upload_ia(video, custom_meta=md)
  File "/usr/local/lib/python3.5/dist-packages/tubeup/__main__.py", line 128, in upload_ia
    with open(json_fname) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/USER/.tubeup/downloads/Green_Day_s_Bang_Bang_Video_Directed_By_Tim_Armstrong._Here_s_A_Behind_Th...-10154561156789521v.info.json'

**Comment by vxbinaca** [comment] 2017-10-06 05:17
This problem is known of but occurs too intermittently to properly diagnose. I've gotten a proper video URL and most of the time get a proper rip and upload.

**Comment by dkl3** [comment] 2017-10-06 23:14
It just says that the info.json isn't found.

**Comment by vxbinaca** [comment] 2017-10-06 23:17
Then we need a failsafe that just uploads the files anyway even without the Metadata

**Comment by jjjake** [comment] 2017-10-07 00:35
I would recommend **not** uploading items without metadata, FWIW.

An alternative would be to force the user to add their own own metadata via `--metadata`.

**Comment by vxbinaca** [comment] 2017-10-07 02:38
Maybe there's something wrong with the Facebook extractor in youtube-dl. Let me examine what's going on with that particular extractor and file a bug report if necessary

**Comment by vxbinaca** [comment] 2017-12-03 04:45
It's been nearly 2 months. This issue is difficult for me to consistently reproduce, and I haven't been able to reproduce it at all in more than a month. I think this may have been an issue with a dependency of tubeup. Closing.

**Comment by vxbinaca** [comment] 2017-12-03 06:34
Re-opening because somewhere between 0.0.10 and 0.0.12, something broke.

**Closed** 2018-01-22 09:27 UTC
