### ISSUE TITLE
GUI for inexperienced users

### ISSUE THREAD

**Issue by Flashfire42** [bibanon/tubeup#100] opened 2019-07-10 05:52 UTC
Unlikely to be an implemented feature but a GUI for people who are inexperienced with the CLI could be useful to get more archiving done.

**Comment by vxbinaca** [comment] 2019-07-10 05:58
What do you not understand? I mean we need better documentation but is there a question you have?

**Comment by antonizoon** [comment] 2019-07-10 06:03
It's going to probably suck to hear this but the command line hoops to jump through for the general public *is a feature, not a bug.* It's already a mess with the amount of people transferring whatever videos are on YouTube to the Internet Archive already, when that simply isn't possible: only those at threat or the cream of the crop can be picked out.

**Comment by vxbinaca** [comment] 2019-07-10 06:10
I agree with Antonizoon that the tool is abused but I want to hear your questions you have.

**Comment by Flashfire42** [comment] 2019-07-10 09:09
My main goal is to archive unlisted videos that appear in ads as I feel like they are overlooked by archivists. I am on a windows device and simply dont know if I have the time to learn the CLI at this point. A GUI might help me to understand what is actually happening so that I may be able to further achieve my goal. Coding usually requires logical thinking and that's something I struggle with as an abstract thinker.

**Comment by vxbinaca** [comment] 2019-07-10 09:12
IA staff will likely ban you for archiving ads like that.

**Comment by Flashfire42** [comment] 2019-07-10 09:18
yikes ok. duly noted. I have other stuff I would like to archive. Some news stuff for example. But the learning curve for me is currently too steep.

**Comment by vxbinaca** [comment] 2019-07-10 09:20
Copyrighted news casts or just relevant videos?

**Comment by Flashfire42** [comment] 2019-07-10 09:22
Some of each. I would assume that some of the videos get darked but for them to be saved is the main goal

**Comment by vxbinaca** [comment] 2019-07-10 09:24
We have a guy who's doing limited state videos. Alt-censored.com

**Comment by Flashfire42** [comment] 2019-07-10 09:26
That site is dead unless I am missing something

**Comment by vxbinaca** [comment] 2019-07-10 09:30
Here: https://www.altcensored.com

Trust me you're not the first person to have your idea, nor to attempt to act on it. Others including myself have it covered.

**Comment by Flashfire42** [comment] 2019-07-10 09:36
Do we have a project for unlisted videos outside of unlistedvideos.com ads are often done this way and are likely to change or vanish at any time. If we do then you can go ahead and close this issue cause while others might want it my offtopic discussion is no longer required

**Comment by vxbinaca** [comment] 2019-07-10 09:48
Archive.org staff - which we are not on this Python project - wouldn't like ads being dumped into the site on a large scale. Please don't do what you proposed. Thanks.

**Closed by vxbinaca** 2019-07-10 09:48 UTC

**Comment by upintheairsheep** [comment] 2021-12-22 04:22
https://github.com/chriskiehl/Gooey

Sadly this needs command line to make and made me cry of overwhelmed once.
